# Generated by Django 5.2.1 on 2025-05-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Recruitment", "Recruitment"),
                            ("Onboarding", "Onboarding"),
                            ("Probation", "Probation"),
                            ("Normal", "Normal"),
                            ("Resigned", "Resigned"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=125)),
                ("last_name", models.CharField(max_length=125)),
                ("address", models.TextField()),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        default="Normal",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.status",
                    ),
                ),
            ],
            options={
                "unique_together": {("first_name", "last_name")},
            },
        ),
    ]
