# Generated by Django 5.2.1 on 2025-05-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.ForeignKey(
                default="Normal",
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.status",
            ),
        ),
    ]
