# Generated by Django 5.2.1 on 2025-05-15 16:26

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command("loaddata", "employee/data/init_status.json", app_label="employee")


def delete_fixture(apps, schema_editor):
    MyModel = apps.get_model("employee", "Status")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=delete_fixture),
    ]

