# Generated by Django 5.2.1 on 2025-05-16 02:52

import django.db.models.deletion
import employee.models.status
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_init_status_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, unique=True)),
                ("salary", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.ForeignKey(
                default=employee.models.status.Status.get_default_status,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.status",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                choices=[
                    ("Recruitment", "Recruitment"),
                    ("Onboarding", "Onboarding"),
                    ("Probation", "Probation"),
                    ("Normal", "Normal"),
                    ("Resigned", "Resigned"),
                    ("Suspended", "Suspended"),
                    ("Terminated", "Terminated"),
                    ("Retired", "Retired"),
                    ("Contract", "Contract"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
